---
- name: Setup Credentials for Controller
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create AWS EC2 Credential
      ansible.controller.credential:
        name: "AWS EC2 Credential"
        credential_type: "Amazon Web Services"
        organization: Default
        state: present
        inputs:
          username: "{{ aws_username }}"
          password: "{{ aws_password }}"
          
    - name: Create SSH Key Credential for EC2
      ansible.controller.credential:
        name: "SSH Key for EC2"
        credential_type: "Machine"
        organization: Default
        state: present
        inputs:
          #ssh_key_data: "{{ lookup('file', '../files/workshop_key') }}"
          ssh_key_data: "{{ workshop_key }}"
          username: "{{ ssh_username }}"
          become_method: sudo